CREATE TABLE [submissions](
[submission_id] int NOT NULL, 
[body] varchar(1000)NOT NULL,
[url] varchar(1000) NOT NULL, 
[grade] varchar(20) NOT NULL, 
[score] int NOT NULL, 
[submitted_at] varchar(25) NOT NULL, 
[assignment_id] int NOT NULL, 
[student_id] int NOT NULL, 
[submission_type] varchar(100) NOT NULL, 
[workflow_state] varchar(100) NOT NULL, 
[grade_matches_current_submission] varchar(100) NOT NULL, 
[graded_at] varchar(100) NOT NULL, 
[grader_id] int NOT NULL,
[attempt] int NOT NULL,
[cached_due_date] varchar(100) NOT NULL, 
[excused] varchar(100) NOT NULL, 
[late_policy_status] varchar(100) NOT NULL, 
[points_deducted] varchar(100) NOT NULL, 
[grading_period_id] varchar(100) NOT NULL, 
[extra_attempts] varchar(100) NOT NULL, 
[posted_at] varchar(100) NOT NULL, 
[redo_request] varchar(100) NOT NULL, 
[late] varchar(100) NOT NULL, 
[missing] varchar(100) NOT NULL,
[seconds_late] int NOT NULL,
[entered_grade] varchar(25) NOT NULL,
[entered_score] int NOT NULL, 
[preview_url] varchar(1000) NOT NULL, 
[anonymous_id] varchar(100) NOT NULL, 
[external_tool_url] varchar(1000) NOT NULL
)
GO